---
title: Prison Book Program Genre Request Analysis and Results
author: Matthew Carroll
output: word_document
---

# Prison Book Program Genre Request Analysis

Following an award by the organization Better World Books, Prison Book Program (PBP) set out to determine the most frequently requested genres received from those served. The book acquisition committee charged with finding and acquiring the most impactful books able to be purchased with this award has thus strived to isolate the types of books both donated by community members and the books requested by customers. This document attempts to provide an analysis and report of the results of the latter half: the requests. 

## Gathering the Data

The data was acquired from letters processed between the months of May and July 2025. At the time we had a roughly 5 month backlog so letters were being sent by customers approximately between the months of November 2024 and February 2025. All of the letters were given to analysis directly after passing quality control (QC) and officially being having an associated package sent out. This means no letters rejected from individuals we cannot serve, letters that were processed by Mike (i.e. letters from New England), nor letters that only requested National Prisoner Resource Lists (NPRLs) or the Insider Guide to Jailhouse Law (IGJL, formerly We the People: Legal Primer) that were split from the request tray prior to verification were included in the analysis. Notably, these letters do specifically include Special Requests processed within the May to July timeframe as well as standard Normal and Bundle letters. The vast majority of letters analyzed are normal letters in an effort to spread out analysis across prisons and across the country and reduce overlap that is expected to occur within prisons (i.e. bundles might contain groups wanting to determine a book club and requesting the same book). It is known, however, that because of the verification process that works alphabetically state-by-state, the letters that are picked within any one session may have regional similarities. 

Counting requests was a time intensive and arduous process. After recieving batches of letters from the QC tray gathered over the course of a week, each letter was again read one-by-one and the requested genre was marked.

### Genres

Each letter started with the same initial genre set. This genre set was provided upon the outset by the Prison Book Program and is used to both categorize and identify picking locations for books. While not perfectly up-to-date, it forms the basis for the letters to be assigned a genre and additional categories could be added if necessary. 

Below is the provided list of genres curated by PBP alongside the assumed priority prior to this work. It is sorted first by priority then alphabetically by genre.

| All Genres | Priority | Category |
|------------|----------|----------|
| Art how to | Highest | Nonfiction |
| Comics | Highest | Fiction |
| Dictionaries | Highest | Nonfiction |
| Exercise | Highest | Nonfiction |
| Health & wellness (general) | Highest | Nonfiction |
| Language learning | Highest | Nonfiction |
| Law | Highest | Nonfiction |
| LGBTQ+ | Highest | Fiction |
| LGBTQ+ | Highest | Nonfiction |
| Manga | Highest | Fiction |
| New age | Highest | Nonfiction |
| Religion (non-mainstream) | Highest | Nonfiction |
| RPG | Highest | Nonfiction |
| Trade skills | Highest | Nonfiction |
| Alternative care practices | High | Nonfiction |
| Business how to | High | Nonfiction |
| Career/jobs | High | Nonfiction |
| Coloring books | High | Nonfiction |
| Computers & technology | High | Nonfiction |
| Cooking & food | High | Nonfiction |
| Fantasy | High | Fiction |
| Graphic Novels | High | Fiction |
| Health conditions | High | Nonfiction |
| History (native/indigenous, ancient, war, Northern Europe) | High | Nonfiction |
| Hobbies | High | Nonfiction |
| Homesteading/off-grid | High | Nonfiction |
| Horror | High | Fiction |
| Investing how to | High | Nonfiction |
| Large print | High | Nonfiction |
| Large print | High | Fiction |
| Mental health/self help | High | Nonfiction |
| Military/veterans | High | Nonfiction |
| Mystery/detective | High | Fiction |
| Nutrition | High | Nonfiction |
| Paranormal | High | Fiction |
| Personal finance | High | Nonfiction |
| Prison memoir/support | High | Nonfiction |
| Puzzle/activity books | High | Nonfiction |
| Real estate | High | Nonfiction |
| Religion (mainstream) | High | Nonfiction |
| Science | High | Nonfiction |
| Science fiction | High | Fiction |
| Thriller/suspense/spy | High | Fiction |
| Urban | High | Fiction |
| Vehicles | High | Nonfiction |
| Westerns | High | Fiction |
| Writing | High | Nonfiction |
| Activism & social change | Medium | Nonfiction |
| Adventure | Medium | Fiction |
| Animals | Medium | Nonfiction |
| Asian cultures | Medium | Fiction |
| Black culture | Medium | Fiction |
| Christian | Medium | Fiction |
| Comedy/humor | Medium | Fiction |
| Dramatic novels | Medium | Fiction |
| Games other than RPG | Medium | Nonfiction |
| Gardening & plants | Medium | Nonfiction |
| Hispanic cultures | Medium | Fiction |
| LGBTQ+ | Medium | Fiction |
| Math | Medium | Nonfiction |
| Media (film, tv & theatre) | Medium | Nonfiction |
| Military Fiction | Medium | Fiction |
| Myths & legends | Medium | Fiction |
| Native American cultures | Medium | Fiction |
| Philosophy | Medium | Nonfiction |
| Psychology | Medium | Nonfiction |
| Reading | Medium | Nonfiction |
| Romance | Medium | Fiction |
| Speech/public speaking | Medium | Nonfiction |
| Sports | Medium | Nonfiction |
| Sports  | Medium | Fiction |
| Travel | Medium | Nonfiction |
| True adventure | Medium | Nonfiction |
| Art/music history & appreciation | Low | Nonfiction |
| Biography/autobiography | Low | Nonfiction |
| Chick lit/Book Club picks | Low | Fiction |
| Children/adolescent | Low | Fiction |
| Classics | Low | Fiction |
| Coming of age | Low | Fiction |
| Education/study skills | Low | Nonfiction |
| Environment | Low | Nonfiction |
| Essays & short stories | Low | Nonfiction |
| Gender & women's studies | Low | Nonfiction |
| Grief/death | Low | Nonfiction |
| Historical fiction | Low | Fiction |
| History (Middle Eastern, Asian, Latin American, North America) | Low | Nonfiction |
| Parenting | Low | Nonfiction |
| Plays | Low | Fiction |
| Poetry | Low | Fiction |
| Politics | Low | Nonfiction |
| Romance | Low | Fiction |
| Sociology | Low | Nonfiction |

